name: generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-pacman:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate pacman-contribution-graph.svg
        uses: ./.github/actions/pacman-contribution-graph
        with:
          github_user_name: ${{ github.repository_owner }}

      # Push the generated SVG to the output branch
      - name: push pacman-contribution-graph.svg to the output branch
        uses: ./.github/actions/ghaction-github-pages
        with:
          target_branch: output
          build_dir: dist
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}