name: generate 3D Contrib

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-3d-contrib:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate 3D-Contrib SVG
        uses: ./.github/actions/github-profile-3d-contrib
        with:
          github_username: ${{ github.repository_owner }}
